#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Derived from WaxFlow codec/g711/g711_test.go and MIT testdata, fork
# github.com/AMWolfstein/WaxFlow at b7857aff88820ad37936026421d1641e64611dbe.
# Copyright (c) 2026 Cole Springer, MIT License (see codecs/THIRD-PARTY-NOTICES).
"""Replicate free mono compressed test samples into 7/8-channel WAV, outside the repo.
PCM expectations must subsequently be generated by scripts/waxflow-oracle.sh.
Usage: python3 scripts/waxflow-g711-corpus.py EXTERNAL_WAXFLOW_CLONE EXTERNAL_CORPUS
"""
import pathlib, struct, sys
src, corpus = map(pathlib.Path, sys.argv[1:])
repo = pathlib.Path(__file__).resolve().parent.parent
if corpus.resolve().is_relative_to(repo):
    raise SystemExit('Corpus must be outside the repository')
for law, tag in [('alaw', 6), ('ulaw', 7)]:
    raw = (src / 'testdata' / ('sine-' + law + '.wav')).read_bytes()
    chunks = {}; pos = 12
    while pos + 8 <= len(raw):
        name, size = struct.unpack_from('<4sI', raw, pos)
        chunks[name] = raw[pos + 8:pos + 8 + size]; pos += 8 + size + (size & 1)
    original_tag, channels, rate = struct.unpack_from('<HHI', chunks[b'fmt '])
    assert original_tag == tag and channels == 1
    for channels in (7, 8):
        data = b''.join(bytes([b]) * channels for b in chunks[b'data'])
        fmt = struct.pack('<HHIIHHH', tag, channels, rate, rate * channels, channels, 8, 0)
        def chunk(name, body):
            return name + struct.pack('<I', len(body)) + body + b'\0' * (len(body) & 1)
        body = b'WAVE' + chunk(b'fmt ', fmt) + chunk(b'fact', struct.pack('<I', len(chunks[b'data']))) + chunk(b'data', data)
        target = corpus / 'waxflow-g711-tests' / ('sine-' + law + '-' + str(channels) + 'ch.wav')
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(b'RIFF' + struct.pack('<I', len(body)) + body)
